// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUhezWt4NaAK8Q2c013CFDOb_g8ZJapJk',
    appId: '1:128546733017:web:46379ce25021ebc16ff7c8',
    messagingSenderId: '128546733017',
    projectId: 'orders-51754',
    authDomain: 'orders-51754.firebaseapp.com',
    storageBucket: 'orders-51754.appspot.com',
    measurementId: 'G-3V9ZGZL6TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF4T56OFyibchy9hKXKalseekUuTCZ-wg',
    appId: '1:128546733017:android:b5d5654658d7d60b6ff7c8',
    messagingSenderId: '128546733017',
    projectId: 'orders-51754',
    storageBucket: 'orders-51754.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4OZpszu7JKIF3puzTfCowrdKiAslf16I',
    appId: '1:128546733017:ios:1e5914c38dbbe29b6ff7c8',
    messagingSenderId: '128546733017',
    projectId: 'orders-51754',
    storageBucket: 'orders-51754.appspot.com',
    iosClientId: '128546733017-k6e2op8ppcrgo4c8kent54gsgqta8ovj.apps.googleusercontent.com',
    iosBundleId: 'com.example.orders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4OZpszu7JKIF3puzTfCowrdKiAslf16I',
    appId: '1:128546733017:ios:1e5914c38dbbe29b6ff7c8',
    messagingSenderId: '128546733017',
    projectId: 'orders-51754',
    storageBucket: 'orders-51754.appspot.com',
    iosClientId: '128546733017-k6e2op8ppcrgo4c8kent54gsgqta8ovj.apps.googleusercontent.com',
    iosBundleId: 'com.example.orders',
  );
}
